# Generated by Django 5.2.5 on 2025-09-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(editable=False, verbose_name='Порядковый номер в альбоме'),
        ),
    ]
