# Generated by Django 5.2.5 on 2025-09-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['year']},
        ),
    ]
