# Generated by Django 5.2.5 on 2025-09-04 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(64)], verbose_name='Название'),
        ),
    ]
